sillsdev/chorus

src/LibChorus/merge/xml/generic/FindNodeToMerge.cs, src/LibChorus/notes/Message.cs, src/LibChorusTests/notes/MessageTests.cs
Cherry picks of the latest two changes fixed during FlexBridge development
=> Cherry pick fb fixes

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
* Remove the setting of extensions in the mercurial.ini since
they are made redundant by our setting them in every repository
=> Remove unnecessary mercurial.ini manipulation

src/Installer/ChorusMergeModule.wxs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
After making several mistakes I have learned the reasons for all the things I removed this Monday.
This PR reverts two changes and makes a different fix for the installer problem.
=> Repent and fix merge module

src/ChorusHubTests/ChorusHubTests.cs, src/LibChorus/Utilities/ProcessOutputReader.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
Hopefully the last change required to get backward compatibility of chorus repositories to work.
=> Backward compatibility the sequel

src/LibChorusTests/VcsDrivers/Mercurial/Utf8Tests.cs
* Change test to follow desired code path
* Make test more specific to the desired failure
* Make test run on Linux
=> Fix failing CloneLocalWithoutUpdate test

src/LibChorus/sync/CommitCop.cs, src/LibChorus/sync/Synchronizer.cs, src/LibChorusTests/sync/CommitCopTests.cs
* Change the place where validation happened so new files get
checked.
* Add unit tests for verifying this change
=> Make CommitCop validate files on first addition to a repo

InstallChorusHubService.bat, UninstallChorusHubService.bat, build/TestInstallerBuild.bat, src/Installer/ChorusHub.wxs
The hg.exe running as a service is what receives the incoming requests
* Add hg firewall rule to ChorusHub.wxs
* Update testing batch files to work with a modern VisualStudio
=> Add firewall rule for hg to ChorusHub service install

src/Chorus/UI/Settings/SendReceiveSettings.Designer.cs, src/Chorus/UI/Settings/SendReceiveSettings.cs, src/Chorus/UI/Settings/SendReceiveSettings.resx
* Navigate control to temp html file after the form is shown
* Disable browser shortcuts and right click menu items
=> Fix for FlexBridge LT-16597, instructions blank on Linux

src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs
If one chunk in a pull fails, retry; don't mark the whole pull as a failure.
=> Do Not Fail the Pull if One Chunk Fails

src/Chorus/UI/Settings/SendReceiveSettings.cs, src/Chorus/UI/Settings/SendReceiveSettings.resx
Link to a webpage where the user can
download the PDF, since we can't link to a
file without crashing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/74)
=> LT-16617: Change Link to Tech Notes PDF on Linux

src/Chorus/UI/Notes/AnnotationEditorView.Designer.cs, src/Chorus/UI/Settings/SendReceiveSettings.cs, src/Chorus/UI/Settings/SendReceiveSettings.resx, src/Chorus/UI/Sync/SyncStartControl.cs, src/Chorus/UI/Sync/SyncStartModel.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
Also allow l10n of status strings for Internet, CH, and USB.
=> Allow Localization of Chorus Hub Setup Instructions HTML

src/Chorus.Tests/UI/Misc/ServerSettingsModelTests.cs, src/Chorus/UI/Misc/ServerSettingsModel.cs
This is the same bug fix as PR #83 .  You can following the conversation there.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/84)
=> Fix ServerSettingsModel.InitFromUri to use UrlDecode

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/LibChorus/VcsDrivers/Mercurial/Revision.cs, src/LibChorusTests/VcsDrivers/Mercurial/HgWrappingTests.cs, src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/90)
=> Move some new functionality from Flex Bridge to Chorus

src/LibChorusTests/VcsDrivers/Mercurial/HgVersionBranchingTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/93)
=> Enable test that no longer fails on mono

src/ChorusHub/ChorusHubService.cs, src/LibChorus/ChorusHub/IChorusHubService.cs
There are no changes to existing API methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/94)
=> PTX-41359 add API methods required for support PTX send/receive requirements

build/buildupdate.mono.sh, build/buildupdate.win.sh, build/readme - making buildUpdate script.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/106)
=> Update build update scripts after change to get L10NSharp from libpalaso

.gitignore, lib/Debug/icu.net.dll.config, lib/Release/icu.net.dll.config, src/LibChorus/LibChorus.csproj, src/LibChorus/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/108)
=> Get icu.net from nuget package

src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs
Continue using all base revisions to construct the BundleID filename, but use a hash to ensure fixed filename length
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/116)
=> Rehash BundleID

src/LibChorus/FileTypeHanders/ldml/LdmlFileHandler.cs
The terminal Z in a date denotes UTC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/117)
=> Tolerate Terminal Z in LDML file dates

src/Chorus/UI/Clone/GetCloneFromInternetModel.cs, src/Chorus/UI/Misc/ServerSettingsControl.cs, src/LibChorus/Model/ServerSettingsModel.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/LibChorusTests/Model/ServerSettingsModelTests.cs
This PR adds 3 new HTTPS entries into the server list in the Chorus Settings dialog:
- resumable [secure]
- private [secure + safe mode]
- public [secure + safe mode]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/107)
=> Languagedepot SSL

build/buildupdate.mono.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/124)
=> Fix buildupdate.mono.sh for Libpalaso Linux build renaming (chorus-2.5)

build/Chorus.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/129)
=> Investigate crash when running tests on TC

build/buildupdate.win.sh, src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus.csproj, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusHubTests/ChorusHubTests.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj, src/SampleApp/SampleApp.csproj, src/Tests-ChorusPlugin/Tests-ChorusPlugin.csproj
* Modified the project file to support 64bit
* In buildupdate sh file modified libpalaso
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/133)
=> Fix : LT-18380 Chorus build for AnyCPU and 64-bit build

src/Installer/ChorusHub.wxs, src/Installer/ChorusMergeModule.wxs
installer build fails not caught it before the continuous build got this far
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/138)
=> get icu files for installer from output dir

src/LibChorusTests/LibChorus.Tests.csproj, src/LibChorusTests/packages.config, src/SampleApp/SampleApp.csproj, src/SampleApp/packages.config
includes eb's fix for fastzip to extract correctly on linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/141)
=> use ICSharpCode.SharpZipLib.Patched

src/LibChorus/LibChorus.csproj, src/LibChorus/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/142)
=> update to icu 2.2.0 to match libpalaso-2.6

build/Chorus.proj, build/buildupdate.mono.sh, build/buildupdate.win.sh, src/LibChorus/FileTypeHandlers/lift/LiftSynchronizerAdjunct.cs, src/LibChorus/LibChorus.csproj, src/LibChorusTests/FileHandlers/Lift/LiftSynchronizerAdjunctTests.cs, src/LibChorusTests/LibChorus.Tests.csproj
* Adjust GetBranchNameFromLiftFile to append _ldml3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/143)
=> LT-18674 Update to 0.13_ldml3 chorus branch on ldml v3 projects

Chorus.sln
also should be merged into master which has the same issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/153)
=> build ChorusHubApp on DebugMono and ReleaseMono

src/LibChorus/merge/xml/generic/FindNodeToMerge.cs
* All childnodes of a parent will be checked for matching key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/154)
=> Fix LT-14385 Store all valid merge candidate childnodes.

lib/common/UpdatingMercurial.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/155)
=> Add note about zipping from Windows to instructions

src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/157)
=> Add any error info reported by the server into progress window

build/buildupdate.mono.sh, build/buildupdate.win.sh, src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, src/LibChorus/FileTypeHandlers/lift/LiftMerger.cs, src/LibChorus/LibChorus.csproj, src/LibChorus/VcsDrivers/Git/GitRepository.cs, src/LibChorus/VcsDrivers/Mercurial/BundleStorageManager.cs, src/LibChorus/merge/ChangeReport.cs, src/LibChorus/merge/DefaultChangeReport.cs, src/LibChorus/merge/IChangeReport.cs, src/LibChorus/merge/xml/generic/Conflict.cs, src/LibChorus/merge/xml/generic/XmlUtilities.cs, src/LibChorus/notes/Annotation.cs, src/LibChorus/notes/Message.cs
This replaces PR #161.
(I thought we could use the `chorus-2.6` branch instead of maintaining a `lfmerge` branch, but I overlooked that the former uses libpalaso 3.1 which we can't use in lfmerge yet. Therefore I'm re-creating this PR agains the `lfmerge` branch)
This change requires the libpalaso changes from [#602](https://github.com/sillsdev/libpalaso/pull/602).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/163)
=> Add property to get GUID of the status message

src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/165)
=> Ignore test on TC

src/LibChorus/LibChorus.csproj, src/LibChorus/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/167)
=> Update icu.net and Icu4c.Win.Min packages

src/ChorusHub/ChorusHubService.cs, src/ChorusHubApp/ChorusHubApp.csproj, src/LibChorusTests/FileHandlers/Lift/LiftSynchronizerAdjunctTests.cs, src/LibChorusTests/LibChorus.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/172)
=> Update code to support libpalaso 4.1 API changes

src/LibChorus/LibChorus.csproj, src/LibChorus/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/174)
=> use icu.net 2.3.2 (chorus-2.5)

src/LibChorus/LibChorus.csproj, src/LibChorus/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/173)
=> use icu.net 2.3.2 (chorus-2.6)

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/185)
=> Use system certificate file on Linux

src/LibChorus/FileTypeHandlers/ChorusFileTypeHandlerCollection.cs, src/LibChorus/Utilities/ini/IniDocument.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/187)
=> Robust file for hrgc save

src/LibChorus/FileTypeHandlers/ldml/LdmlFileHandler.cs, src/LibChorus/FileTypeHandlers/xml/XmlAttributeChange.cs, src/LibChorus/merge/xml/generic/FindNodeToMerge.cs, src/LibChorus/merge/xml/generic/MergeAtomicElementService.cs, src/LibChorusTests/FileHandlers/ldml/LdmlFileMergeTests.cs
* Make characters ldml non-atomic and handle the type and
type-less use cases.
* Update existing test cases to deal with the new expectations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/188)
=> Fix some ldml merging issues now that we see more data

build/NuGet.targets, src/LibChorus/Utilities/ini/IniDocument.cs, src/LibChorusTests/VcsDrivers/Mercurial/HgWrappingTests.cs, src/LibChorusTests/sync/Synchronizer.BadSituationTests.cs
TeamCity builds were failing to download NuGet.exe.
Update to the same URL used by libPalaso.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/199)
=> Update NuGet.exe URL

.gitignore, GitVersion.yml, build/Chorus.dep, build/Chorus.proj, src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus-Designer.csproj, src/Chorus/Chorus.csproj, src/Chorus/packages.config, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp-Designer.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusHubApp/packages.config, src/ChorusHubTests/ChorusHubTests.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/ChorusMerge/ChorusMerge.csproj, src/Installer/ChorusHub.wxs, src/Installer/ChorusMergeModule.wxs, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorus/Utilities/ini/IniDocument.cs, src/LibChorusTests/LibChorus.Tests.csproj, src/LibChorusTests/VcsDrivers/Mercurial/HgWrappingTests.cs, src/LibChorusTests/sync/Synchronizer.BadSituationTests.cs, src/SampleApp/SampleApp-Designer.csproj, src/SampleApp/SampleApp.csproj, src/SampleApp/packages.config, src/Tests-ChorusPlugin/Tests-ChorusPlugin.csproj
- use released GitVersionTask instead of hacked one
- update libpalaso packages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/190)
=> Update packages and fix build

build/Chorus.proj, src/Chorus/Chorus.csproj, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj
This is necessary to allow building on AppVeyor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/200)
=> Add default target

src/LibChorus/FileTypeHandlers/ConflictPresenter.cs, src/LibChorus/merge/xml/generic/XmlUtilities.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/203)
=> Fix bugs identified by LGTM

src/LibChorus/notes/AnnotationRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/213)
=> Fix crash in trying to update the annotations on a locked file

src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus.csproj, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj
for our software, including Palaso, build and release tasks, and L10NSharp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/229)
=> Always use the very latest NuGet packages

Directory.Build.targets, README.md, src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus.csproj, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj
after packing, if the local nuget repo is specified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/227)
=> Copy packages to the local nuget repository

src/LibChorus/VcsDrivers/Mercurial/HgResumeRestApiServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/233)
=> Decrypt the password so the server recognizes it

build/Chorus.proj, src/Installer/ChorusMergeModule.wxs, src/Installer/GeneratedMercurial.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/234)
=> Generate a configuration with the installed path for cacert.pem

src/Chorus.Tests/Chorus.Tests.csproj, src/ChorusHubTests/ChorusHubTests.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj, src/Tests-ChorusPlugin/Tests-ChorusPlugin.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/239)
=> Upgrade NUnit and icu.net

src/Chorus/UI/Clone/GetCloneFromInternetModel.cs, src/Installer/ChorusMergeModule.wxs, src/LibChorus/VcsDrivers/RepositoryAddress.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/240)
=> Fix high bandwidth

README.md, src/Chorus/UI/Misc/ServerSettingsControl.Designer.cs, src/Chorus/UI/Misc/ServerSettingsControl.cs, src/Chorus/UI/Settings/SendReceiveSettings.Designer.cs, src/LibChorus/Model/ServerSettingsModel.cs
to retreive a list of projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/235)
=> LT-20540: Allow logging in to the QA server

src/Chorus/UI/Settings/SendReceiveSettings.Designer.cs, src/Chorus/UI/Sync/SyncStartModel.cs, src/LibChorus/Model/ServerSettingsModel.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/LibChorus/VcsDrivers/Mercurial/HgResumeRestApiServer.cs, src/LibChorus/VcsDrivers/Mercurial/IHgTransport.cs, src/LibChorus/VcsDrivers/RepositoryAddress.cs, src/LibChorus/sync/Synchronizer.cs, src/LibChorusTests/Model/ServerSettingsModelTests.cs, src/LibChorusTests/VcsDrivers/Mercurial/HgSettingsTests.cs, src/LibChorusTests/sync/ProxyTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/241)
=> Obscure password in log

src/LibChorus/LibChorus.csproj, src/LibChorus/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/242)
=> Upgrade to the latest ICU.NET

src/Chorus/UI/Clone/GetCloneFromInternetDialog.cs, src/Chorus/UI/Clone/GetCloneFromInternetModel.cs, src/Chorus/UI/Misc/ServerSettingsControl.Designer.cs, src/Chorus/UI/Misc/ServerSettingsControl.cs, src/Chorus/UI/Settings/SendReceiveSettings.Designer.cs, src/Chorus/UI/Settings/SendReceiveSettings.resx, src/LibChorus/Model/ServerSettingsModel.cs, src/LibChorus/VcsDrivers/RepositoryAddress.cs, src/LibChorusTests/Model/ServerSettingsModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/245)
=> LT-20549: Forget Password (MVP)

src/LibChorus/Model/ServerSettingsModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/246)
=> LT-20555: Bad message for bad username

src/LibChorus/Model/ServerSettingsModel.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/LibChorus/VcsDrivers/RepositoryAddress.cs, src/LibChorus/sync/Synchronizer.cs, src/LibChorusTests/LibChorus.Tests.csproj, src/LibChorusTests/VcsDrivers/Mercurial/HgRepositoryTests.cs, src/LibChorusTests/VcsDrivers/RepositoryAddressTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/247)
=> LT-20547: Log additional metadata

src/Chorus/UI/Sync/SyncStartControl.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/LibChorusTests/VcsDrivers/Mercurial/HgRepositoryTests.cs, src/LibChorusTests/VcsDrivers/RepositoryAddressTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/249)
=> LT-19468: remove passwords from hgrc files on S+R

.gitattributes, Chorus.sln, Directory.Build.props, src/Chorus.Tests/Chorus.Tests.csproj, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusHubTests/ChorusHubTests.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorus/Utilities/UrlHelper.cs, src/LibChorusTests/LibChorus.Tests.csproj, src/LibChorusTests/utilities/UrlHelperTests.cs, src/SampleApp/SampleApp.csproj, src/Tests-ChorusPlugin/Tests-ChorusPlugin.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/256)
=> Move common properties to Directory.Build.props

src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/259)
=> Require newer L10nSharp

src/LibChorus/notes/AnnotationRepository.cs
* Catch exception trying to read the LastWriteTime from
the ChorusNotes file and retry
* Ignore failures after the retry instead of crashing
* Fixes FB issue LT-20685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/260)
=> Address ChorusNotes UnauthorizedAccess exception

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
and rename commandToLog to commandForLog
in hopes that its purpose will be clearer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/262)
=> Authenticate using the real password

src/Chorus/Chorus.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorus/merge/xml/generic/ChorusNotesMergeEventListener.cs, src/LibChorusTests/LibChorus.Tests.csproj
+semver:major
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/263)
=> Update to the latest version of palaso libraries

src/Chorus.Tests/ChorusApplicationTests.cs, src/Chorus/Properties/Settings.Designer.cs, src/Chorus/Properties/Settings.cs, src/Chorus/Properties/Settings.settings, src/ChorusHubApp/Properties/AssemblyInfo.cs, src/ChorusHubApp/Properties/Settings.Designer.cs, src/ChorusHubApp/Properties/Settings.cs, src/ChorusHubApp/Properties/Settings.settings, src/ChorusHubTests/ChorusHubTests.cs, src/ChorusHubTests/ChorusHubTests.csproj, src/LibChorus.TestUtilities/ListenerForUnitTests.cs, src/LibChorus.TestUtilities/SystemAssertListener.cs, src/LibChorus/Properties/Settings.Designer.cs, src/LibChorus/Properties/Settings.cs, src/LibChorus/Properties/Settings.settings, src/LibChorus/VcsDrivers/Mercurial/HgNormalTransport.cs, src/LibChorusTests/MiscTests.cs, src/SampleApp/Properties/Settings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/265)
=> Use CrossPlatformSettingsProvider

src/Chorus/Chorus.csproj
PR #256 moved common properties Directory.Build.props but missed `Chorus.csproj`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/266)
=> Use common props file in Chorus.csproj

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/270)
=> Add instructions to register to use the test server

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/LibChorusTests/Model/ServerSettingsModelTests.cs
* Log any caught exceptions
* Log an informative message if the URI is malformed or the password contains reserved characters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/275)
=> Improve logging when testing internet repo connections

src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj
Part of https://jira.sil.org/browse/LT-20973 and https://jira.sil.org/browse/LT-20978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/276)
=> Update L10NSharp to match Palaso

src/Chorus.Tests/Chorus.Tests.csproj, src/Chorus/Chorus.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusHubTests/ChorusHubTests.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj, src/Tests-ChorusPlugin/Tests-ChorusPlugin.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/284)
=> Upgrade to Palaso 10.* and Newtonsoft.Json 13.0.1

src/LibChorus/FileTypeHandlers/ldml/LdmlFileHandler.cs, src/LibChorusTests/FileHandlers/ldml/LdmlFileMergeTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/286)
=> Switch two problematic ldml elements to Atomic

src/LibChorus/FileTypeHandlers/ChorusFileTypeHandlerCollection.cs
If a ReflectionTypeLoadException is thrown by a unit test, include details in the test report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/285)
=> More helpful message for unit test failure

src/LibChorus/notes/AnnotationMutexFactory.cs, src/LibChorus/notes/AnnotationRepository.cs, src/LibChorus/notes/IAnnotationMutex.cs, src/LibChorus/sync/Synchronizer.cs
* In https://jira.sil.org/browse/LT-20807 the problem seems to come up
when multiple processes are trying to write the file
+semver:minor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/287)
=> Fix file locking problem on Chorus Notes (LT-20807)

.github/workflows/dotnet.yml, src/Chorus/Chorus.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/300)
=> Upgrade to Palaso 11 and Mercurial 3.0.3.6

Chorus.sln.DotSettings, src/Chorus/UI/Misc/ServerSettingsControl.Designer.cs, src/Chorus/UI/Misc/ServerSettingsControl.cs, src/LibChorus/Model/ServerSettingsModel.cs
And comment on the use of .languageforge.org
Part of https://jira.sil.org/browse/LT-21209
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/304)
=> Reorder Custom URL outside Language Forge workflow

.github/workflows/dotnet.yml, .github/workflows/test-results.yml, Chorus.sln.DotSettings, README.md, src/Chorus.Tests/UI/notes/AnnotationModelTests.cs, src/Chorus.Tests/UI/notes/MessageTests.cs, src/Chorus/ChorusUIComponentsInjector.cs, src/Chorus/UI/Notes/Html/StyleSheet.cs, src/LibChorus/Utilities/ExecutionEnvironment.cs, src/LibChorus/notes/EmbeddedMessageContentHandlerRepository.cs, src/LibChorus/sync/LargeFileFilter.cs, src/LibChorusTests/FileHandlers/ChorusFileTypeHandlerCollectionTests.cs, src/LibChorusTests/FileHandlers/audio/AudioFileTypeHandlerTests.cs, src/LibChorusTests/FileHandlers/image/ImageFileTypeHandlerTests.cs, src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, src/LibChorusTests/notes/EmbeddedMessageContentHandlerRepositoryTests.cs, src/LibChorusTests/sync/LargeFileFilterTests.cs
* Update Deprecated API calls
* Pin to Ubuntu 20.04 until we can get hg back on the path
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/307)
=> Fix Unit Tests

src/Chorus/Chorus.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge.Tests/ChorusMerge.Tests.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus.TestUtilities/LibChorus.TestUtilities.csproj, src/LibChorus/LibChorus.csproj, src/LibChorusTests/LibChorus.Tests.csproj
+semver: minor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/318)
=> Update PackageReferences to palaso version 12

src/Chorus/UI/Notes/MergeConflictEmbeddedMessageContentHandler.cs, src/LibChorus/merge/xml/generic/Conflict.cs, src/LibChorusTests/merge/xml/generic/XmlMergerTests.cs
* This fixes Fieldworks bug https://jira.sil.org/browse/LT-21086
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/320)
=> Add meta tag so that utf8 is used in conflict details views

src/Chorus/Chorus.csproj, src/Chorus/UI/Settings/SendReceiveSettings.cs, src/ChorusHub/ChorusHub.csproj, src/ChorusHubApp/ChorusHubApp.csproj, src/ChorusMerge/ChorusMerge.csproj, src/LibChorus/Model/ServerSettingsModel.cs, src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, src/SampleApp/SampleApp.csproj
- Fix check for empty project name
- Save internet URL only if logged in
- Autogenerate binding redirects for WinExe and exe projects
Fixes https://jira.sil.org/browse/LT-21462
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/322)
=> Prevent S&R to Internet w/o full URL

src/LibChorus/MercurialLocation.cs
Resolves #340
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/341)
=> Use correct hg executable on Windows
