sillsdev/chorus

build/Chorus.proj

It is confusing to users to download/install ChorusHubInstaller.msi
without it being signed.  Create a new "SignChorusHub" target that
will be run by the Team City build
"ChorusHub master Windows Service Installer-sans publish"
I have tested this change by pointing the above mentioned build
to this change in my fork of this repo.  See build 2.4.14 of that build.

Sign ChorusHubInstaller

---

src/Installer/ChorusMergeModule.wxs

* Delete the section from the merge module source which is
unnecessary after recent Chorus modifications and which is
also invalid (due to cross component linking) in new Wix versions.

Remove unnecessary ini modification from merge module

---

src/LibChorus/VcsDrivers/Mercurial/HgHighLevel.cs
src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs

Backward compatibility testing revealed that the extensions were not
being set properly in a USB clone using Mercurial 3.
* If a MakeCloneFromLocalToLocal is called with alsoDoCheckout
set to false make sure we still get extensions into the hgrc file.
* Add test to minimally verify this.

Fix problem with missing extensions on USB clones.

---

src/ChorusMerge.Tests/ChorusMergeTests.cs
src/LibChorus/LibChorus.csproj
src/LibChorus/Utilities/ExecutionResult.cs
src/LibChorus/Utilities/HgProcessOutputReader.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
src/LibChorus/VcsDrivers/Mercurial/HgRunner.cs
src/LibChorus/merge/xml/generic/Conflict.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgWrappingTests.cs

* Detect and respond to Hg information about file deletion vs change conflicts which could block a merge.
* Create new conflict for this situation.
* Rename ProcessOutputReader to HgProcessOutputReader  to accurately reflect its purpose

Handle whole file deletion vs changed robustly

---

src/LibChorus/VcsDrivers/Mercurial/HgHighLevel.cs
src/LibChorusTests/sync/UsbRepositorySourceTests.cs

* Add the extra --pull parameter required in Hg 3 to make a backward
compatible clone
* Add unit test to verify that the clone has had the dotencode
requirement eliminated

Fully eliminate the dotencode extension in USB clones

---

src/LibChorus/VcsDrivers/Mercurial/HgNormalTransport.cs

We shouldn't have an empty Dispose() method around unless we have
to implement IDisposable because that makes things more confusing
and suggests that we have to dispose objects of this class.

Remove empty Dispose() method

---

build/build.common.proj

During the introduction of the strong name and no strong name
build version downgrades of the chorus libraries happened.
This causes issues upgrading applications that use the chorus merge
module.
* Increase the version of Chorus to 2.5 so that freshly built
installers will not have downgrade issues for chorus assemblies

Increase Chorus version number to 2.5

---

src/ChorusHub/ChorusHub.cs
src/ChorusHub/ChorusHubServer.cs

* Abort the service startup if another ChorusHub is detected on the
network.
* Improve the logging so that all failures are listed as ChorusHub

Abort service start if another Hub is running

---

src/Chorus.Tests/Chorus.Tests.csproj
src/Chorus.Tests/UI/Misc/ServerSettingsDialogTests.cs
src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
src/Chorus/Chorus.csproj
src/Chorus/UI/Clone/GetCloneFromInternetModel.cs
src/Chorus/UI/Misc/ReadinessPanel.cs
src/Chorus/UI/Misc/ServerSettingsControl.cs
src/Chorus/UI/Misc/ServerSettingsDialog.cs
src/Chorus/UI/Settings/SendReceiveSettings.cs
src/ChorusHubTests/ChorusHubTests.cs
src/LibChorus/LibChorus.csproj
src/LibChorus/Model/InternetCloneSettingsModel.cs
src/LibChorus/Model/ServerSettingsModel.cs
src/LibChorusTests/LibChorus.Tests.csproj
src/LibChorusTests/Model/InternetCloneSettingsModelTests.cs
src/LibChorusTests/Model/ServerSettingsModelTests.cs

- move ServerSettingsModel to LibChorus
- add new InternetCloneSettingsModel in LibChorus that has most of
the previous functionality of GetCloneFromInternetModel but is
strictly UI independent (it has a progress object, but that is
UI agnostic)
- derive GetCloneFromInternetModel from InternetCloneSettingsModel
and wrap a few methods that catch errors and display UI to the
user.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/75)

Make server and internet clone models more UI independent 

---

src/LibChorus/sync/Synchronizer.cs
src/LibChorusTests/sync/UsbRepositorySourceTests.cs

Chorus purposefully clones a "bare" repo to a USB drive. Unfortunately, when pushing to an existing USB repo, Chorus performs an update, causing the repo to no longer be "bare". This pull request corrects this inconsistency by no longer performing the update to a USB repo when pushing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/81)

Ensure that an existing target repo on a USB drive is "bare" after sync

---

src/Installer/GeneratedMercurial.wxs

In the upgrade of mercurial the french localization was accidentally included in the windows mercurial zip file. This resulted in some of the responses parsed by Chorus to be unrecognizable. These two commits fix the issue (and were already applied as a hotfix to the 2.5 branch used by the latest stable FLExBridge)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/88)

These two commits allow people using windows in French to S/R to the internet

---

src/LibChorus/Model/ServerSettingsModel.cs
src/LibChorusTests/Model/ServerSettingsModelTests.cs

This fixes a bug in the Chorus Internet Settings Dialog which was reported to me by a WeSay user.  The previous code would allow a situation whereby the user has a password with a special character in it like % that when saved into the password field and then the dialog is re-opened, the password has "grown" in length.  This is caused by the password field not being properly url decoded when extracted from the URL.
A regression test is also accompanied.
You can test this bug in the latest version of either Fieldworks, WeSay or any other app using the Chorus Internet Settings Dialog box.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/83)

Fix ServerSettingsModel.InitFromUri to use UrlDecode

---

src/LibChorus.TestUtilities/XmlTestHelper.cs
src/LibChorus/FileTypeHandlers/ChorusNotesAnnotationMergingStrategy.cs
src/LibChorus/FileTypeHandlers/Lift-Ranges/LiftRangesMergingStrategy.cs
src/LibChorus/FileTypeHandlers/lift/LiftEntryMergingStrategy.cs
src/LibChorus/merge/xml/generic/ImmutableElementMergeService.cs
src/LibChorus/merge/xml/generic/MergeAtomicElementService.cs
src/LibChorus/merge/xml/generic/MergeChildrenMethod.cs
src/LibChorus/merge/xml/generic/MergeLimitedChildrenService.cs
src/LibChorus/merge/xml/generic/XmlMerger.cs
src/LibChorus/merge/xml/generic/XmlUtilities.cs
src/LibChorusTests/FileHandlers/ChorusNotesFileHandlerTests.cs
src/LibChorusTests/merge/xml/generic/ImmutableElementMergeServiceTests.cs
src/LibChorusTests/merge/xml/generic/MergeAtomicElementServiceTests.cs
src/LibChorusTests/utilities/XmlUtilitiesTests.cs

* Fixes FB bug LT-17461
* Change internal api methods to include the parent
of 'our' node so that 'their' content can be imported
In the future it might be worth it to switch all xml use to XDocument
classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/91)

Stop losing changes to 'their' atomic and immutable elements

---

src/LibChorus/sync/CommitCop.cs

If we pass the full path we might get wrong validation failures.
This happened with flexbridge, when the path to the hg root directory
contained the string "Other".
This change passes a relative path (i.e. where the root path is
stripped) to the handler's VaalidateFile() method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/95)

Pass relative file paths when validating files

---

src/LibChorus/FileTypeHandlers/ConflictPresenter.cs

In the absence of any `<meta>` tag specifying an encoding, GeckoFX on Windows defaults to ISO-8859-1 / CP1252, which leads to garbled text when a non-Roman word had a conflict. The data is correctly UTF-8 encoded in the Chorus Notes file, so adding an HTML `<meta>` tag to specify the encoding is enough to solve the issue.
(cherry picked from commit 17c0cd98dafa8c234fb913a9720e0461601c30c0)
Fixes #97.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/99)

Present conflict report HTML as UTF-8

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Certain unexpected user scenarios can result in
the location of ChorusMerge to change after the
information is stored in the hgrc file.
* Reset the mergetool values before every S/R
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/100)

A 'moved' ChorusMerge on a machine breaks S/R

---

src/Chorus/UI/Misc/ServerSettingsModel.cs

That removes some confusion for users since hg.languageforge.org
is a test server. Send/Receive with languageforge is done through
the regular LanguageDepot.org servers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/102)

Rename LanguageForge in server settings drop down

---

src/LibChorus/FileTypeHandlers/xml/XmlDeletionChangeReport.cs
src/LibChorusTests/FileHandlers/xml/XmlDeletionChangeReportTests.cs
src/LibChorusTests/LibChorus.Tests.csproj

Also fix the reported message to report the actual reported node
(as the message states) instead of the parent node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/109)

Fix a crash in XmlBothDeletionChangeReport

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Previously we did this only on Windows, but it makes sense on
Linux as well and helps with line ending normalization when tests
check in a hg repo for unit testing purposes (like LfMerge does).
To normalize line endings in the hg repo, add the extension `eol`
to the `.hgrc` file and tell eol to always normalize line endings:
[eol]
only-consistent = False
[extensions]
eol =
To have an effect the hg repo also needs a `.hgeol` file:
[repository]
native = LF
[patterns]
** = native
If there is no `.hgeol` file in the hg repo the behavior won't
change and no line ending normalization will happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/111)

Always add eol extension

---

src/LibChorus/notes/Annotation.cs

This is needed for Language Forge Send/Receive, where comments created in Language Forge will have pre-existing GUIDs and we will want to create Annotations with the same GUID. This way, the annotation in Chorus Notes and the comment in Language Forge will be trackable as being the same object, and if the comment is resolved in FLEx then the corresponding comment in Language Forge can be marked as closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/112)

Allow specifying annotation GUID in constructor

---

src/Chorus.Tests/UI/Clone/GetCloneFromUsbDialogTests.cs
src/Chorus.Tests/clone/ClonerTests.cs
src/Chorus/UI/Clone/CloneFromUsb.cs

With this change corrupt repositories on a USB drive appear as follows:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/110)

Inform users about corrupt USB Repos instead of crashing

---

src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs

Omit blatantly redundant parts of a150-character filename.
TODO in a follow-up: remove further name parts to get a fixed-length
name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/113)

Avoid too-long filename (LT-18093)

---

src/LibChorus/VcsDrivers/Mercurial/BundleStorageManager.cs
src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs
src/LibChorus/VcsDrivers/Mercurial/PullStorageManager.cs
src/LibChorus/VcsDrivers/Mercurial/PushStorageManager.cs
src/LibChorusTests/VcsDrivers/Mercurial/PullStorageManagerTests.cs

* Omit all Base Revision hashes from Bundle ID.
The last Base Revision hash is already in the directory path (in most cases), and the files are deleted immetiately on a successful S/R, so the Tip hash should be sufficiently unambiguous.
* Clean up the internal BundleStorageManager API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="16" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/115), and should be reviewed by someone who's worked on something other than FLEx.

Clean up Bundle ID

---

src/LibChorus/sync/Synchronizer.cs

LT-18276, which we cannot reproduce
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/118)

Don't modify SourcesToTry when iterating over them

---

src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgResumeTransportTests.cs

This PR does 3 three things:
- Increases the timeout variable to 30 seconds
- Increases the target time variable to 7 seconds
- Increases the maximum chunk size variable to 20MB
Increasing the timeout to 30 seconds should help reduce the number of "pull timeout, retrying..." messages that chorus users see on bigger projects.
Increasing the target time variable and the chunk size variable should allow for increased data transfer performance
This change was previously discussed here: #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/122)

increase resumable timeout to 30 seconds, target time to 7 seconds, and maximum chunk size to 20MB

---

src/Chorus/UI/Notes/ConflictDetailsForm.cs

Fix : LT-18129 Crash on Conflict Details dialog
* Removed the WebBrowser Copy execution
* Included the Clipboard copy function
* Now it will work on linux also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/131)

Fix : LT-18129 Crash on Conflict Details dialog

---

src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs

the tests create an empty file for the mercurial binary in the test dir but hard coded hg instead of using hg.exe on windows
missing eol extension in the test ini file data on windows
The change to RepositoryRecoversFromIncompleteMerge may not be necessary but allows it to work with older builds of libpalaso than the one that will come from the libpalaso PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/137)

fix mercurial repo tests on windows

---

src/ChorusMerge.Tests/ChorusMergeTests.cs
src/ChorusMerge/ChorusMerge.csproj
src/ChorusMerge/Program.cs

Invert the Prefer32bit option
* Prefer32bit for ChorusMerge unless x64 is the Platform
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/146)

Fix test failures on chorus master build

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

* AsyncLocalCheckIn_NoHgLockWarningWithMultipleWorkers
revealed an issue with multi threaded access of the hgrc
file. This will fix the flaky test and any real user problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/150)

Fix file access issue in multi-threaded Sync

---

src/Chorus/ChorusHubClient.cs
src/Chorus/UI/Clone/GetCloneFromChorusHubDialog.cs

* Increase timeout waiting for ChorusHub server
to return information about projects to 15m
* Add wait cursor for the Clone dialog when waiting
for this response.
In the future we should cache this information in ChorusHubServer
to avoid such a long response time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/152)

Fix FlexBridge crash discovered in PNG

---

src/LibChorus/FileTypeHandlers/ldml/LdmlFileHandler.cs

* Account for collation nodes deleted from ancestor file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/164)

Avoid adding the type attribute to collation during PreMerge

---

Chorus.sln
src/LibChorus/FileTypeHandlers/lift/LiftMerger.cs
src/LibChorus/FileTypeHandlers/lift/LiftUtils.cs
src/LibChorus/merge/xml/generic/ChorusNotesMergeEventListener.cs
src/LibChorus/merge/xml/generic/Conflict.cs
src/LibChorus/merge/xml/generic/XmlUtilities.cs
src/LibChorus/notes/Annotation.cs
src/LibChorus/notes/Message.cs

This is PR #125, but merging into master to make sure the bug stays fixed in future versions of Chorus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/160)

Always write timestamps with time zones

---

src/Installer/ChorusMergeModule.wxs

using x86 dlls
the dlls moved in the newer nuget package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/168)

icu dlls from nuget in arch dep dir

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

* In certain error situations the log gets filled with thousands
of line feeds making the debugging difficult.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/169)

Attempt to eliminate spurious newlines from log

---

src/Chorus/ChorusSystem.cs

L10NSharp now supports selecting the translation memory in the API rather than by having two different branches.
This change adds a new overload of `ChorusSystem.SetUpLocalization` that allows to select the translation memory, and changes the existing method to use TMX files, which is what we had previously. This is necessary to retain previous functionality - previously you could exchange the L10NSharp.dll to select the translation memory. Now this can be done by passing an additional parameter to `SetupLocalization`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/186)

Adjust for new L10NSharp version

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Setting up extensions can fail in multiple places. Adding the exception we catch as inner exception might help to track down some problems.
In particular I'm trying to track down why we have some tests that fail in the `feature/nuget` branch (that used to have all tests passing until I merged with master) but pass in `master`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/198)

Improve exception when failing to set up extensions

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

If a user does a Send/Receive with a very large amount of
binary files the local commit its self could take more then
the 15 minute time out.
* Add an Environment variable override option
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/205)

Use Environment var for timeout to fix problems described in LT-19898

---

src/LibChorus/merge/xml/generic/Conflict.cs
src/LibChorusTests/FileHandlers/LargeFileIntegrationTestService.cs
src/LibChorusTests/merge/xml/generic/ConflictIOTest.cs

* Drop any invalid UTF8 sequences before writing the
HtmlDetails of a conflict to ChorusNotes
* Fix some misspellings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/206)

Fix LT-20017: Sanitize HtmlDetails

---

src/Chorus.Tests/UI/Clone/TargetFolderControlTests.cs
src/Chorus/UI/Clone/TargetFolderControl.cs
src/LibChorus/Model/InternetCloneSettingsModel.cs

* trim at start is easy,
* trim at end is trickier, because we want to allow the
user to enter spaces in between words in the name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/207)

LT-19858 Trim Path in Get Project from Colleague

---

src/Chorus.Tests/ChorusSystemUsage.cs
src/Chorus/UI/Notes/Bar/NotesBarModel.cs
src/Chorus/UI/Notes/Browser/NotesInProjectViewModel.cs
src/LibChorus/notes/AnnotationIndex.cs
src/LibChorus/notes/AnnotationRepository.cs
src/LibChorus/notes/IAnnotationRepositoryObserver.cs
src/LibChorusTests/notes/AnnotationRepositoryTests.cs
src/LibChorusTests/notes/MultiSourceAnnotationRepositoryTests.cs

Changes to notes made in FLEx show up in View Conflicts app, and as a result, changes made there won't overwrite ones from FLEx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/209)

Watch for FLEx changing Notes files (LT-20074)

---

src/LibChorus.TestUtilities/XmlTestHelper.cs
src/LibChorus/merge/xml/generic/MergeLimitedChildrenService.cs
src/LibChorusTests/merge/xml/generic/MergeLimitedChildrenServiceTests.cs

- Import "their" nodes into "our" document before trying to Append them
- Create separate XmlDocuments for theirs, ours, and ancestor for tests
- Test all fixed Appends
- Clean up some tests
Resolves https://jira.sil.org/browse/LT-20282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/219)

Prevent crash copying nodes to other XML documents (LT-20282)

---

src/LibChorus/FileTypeHandlers/ldml/LdmlFileHandler.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
src/LibChorus/merge/xml/generic/HumanLogMergeEventListener.cs
src/LibChorus/merge/xml/generic/XmlUtilities.cs
src/LibChorusTests/FileHandlers/ldml/LdmlFileMergeTests.cs

Partial fix for Flex bug LT-20473
* If only the date has changed just update the file to
contain the most recent timestamp
* Write out ldml files only once, and only when changes
were made
* Update tests where the previous code caused unnecessary
date changes
* Unrelated: Improved visibility for failures to push by
changing the color to RedOrange
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/225)

Improve ldml file merging when only the date changes

---

src/LibChorus/LibChorus.csproj

This change prevents the dlls from Icu4c.Win.Min and SIL.Chorus.Mercurial to automatically get copied to the output directory when a client consumes the LibChorus nuget package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/226)

Don't automatically copy files from Icu4c and Mercurial

---

Chorus.sln.DotSettings
src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
src/LibChorus/Model/ServerSettingsModel.cs
src/LibChorus/Utilities/UrlHelper.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
src/LibChorus/VcsDrivers/Mercurial/HgResumeRestApiServer.cs
src/LibChorus/VcsDrivers/RepositoryAddress.cs
src/LibChorusTests/Model/InternetCloneSettingsModelTests.cs
src/LibChorusTests/Model/ServerSettingsModelTests.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgResumeRestApiServerTests.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgSettingsTests.cs
src/LibChorusTests/utilities/UrlHelperTests.cs

* Change LanguageDepot.org projects to use LanguageForge.org
* Convert former LanguageDepot.org projects to https://
* Remove credentials from all URL's; store them securely in user settings
* Completes https://jira.sil.org/browse/LT-20407 and LT-20535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/230)

Convert LanguageDepot projects to use LanguageForge

---

src/LibChorus/Model/ServerSettingsModel.cs
src/LibChorusTests/Model/ServerSettingsModelTests.cs

* When initializing server settings from a URI containing a project ID, display it without requiring the user to log in
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/231)

Always display Project ID for existing projects

---

src/LibChorus/Model/ServerSettingsModel.cs
src/LibChorus/Utilities/WebResponseHelper.cs

One user has access 200+ projects, and the response headers contain no content length. This tries to read the stream anyway, allowing all projects to be displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/232)

Read Indefinite-sized Responses

---

src/LibChorus/merge/xml/generic/xmldiff/XmlDiff.cs
src/LibChorusTests/FileHandlers/ldml/LdmlFileMergeTests.cs
src/LibChorusTests/merge/xml/generic/xmldiff/XmlDiffTests.cs

* Add string comparison diff for CDATA nodes
* Fixes FieldWorks bug LT-20502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/236)

Fix problem merging changes in CDATA content

---

src/Chorus/UI/Clone/GetCloneFromInternetModel.cs

A client was using it. This undoes one of several
+semver:breaking changes from the previous commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/244)

[API] Reintroduce default GetCloneFromInternetModel ctor

---

build/Chorus.proj

Building the ChorusHubInstaller should not depend on running the
unit tests but instead on the compile (build) step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/255)

Fix ChorusHubInstaller build

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

The Send/Receive code does a lot of `hg log -rREV --template "{node}"` calls in order to learn the long hash of a revision number. This happens very often during a Send/Receive process: the Chorus logs are full of `hg log -r0` operations. Thing is, every single call to `hg log` incurs a cost as a Python process has to be spun up every time this happens. And in any given repository, a specific revision number wil always refer to the same revision with the same long hash, so each long hash only has to be calculated *once* for any given revision number. So we'll cache the output of `log -rREV` operations and return the cached output if the same operation runs a second time. (Other operations like `hg parents` aren't safe to cache, as their result will change during a Send/Receive operation …

Speed up Send/Receive operations significantly

---

src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs

Move the location of the local Chorus cache from AppData to the
specific FLEX or WeSay project.  The problem we were seeing was when
the cache in AppData was being used by two applications; in this
case FLEX and WeSay. (Note that the same problem would exist if two
local WeSay projects or two local FLEX project were using the same
Chorus Project ID.)
When the cache was more up to date than the local FLEX or WeSay
project we would see the error described in the defect. To prevent
this problem we now store the cache in the local FLEX or WeSay
project folder, along with the other project information. This
results in one cache per application/project, so the cache should
never have more up to date chorus data than the local FLEX or
WeSay project.
https://jira.sil.org/browse/LT-20999
---
This …

LT-20999: Move the location of the local Chorus cache

---

src/Chorus/UI/Clone/GetCloneFromInternetDialog.Designer.cs
src/Chorus/UI/Clone/GetCloneFromInternetDialog.cs
src/Chorus/UI/Misc/ServerSettingsControl.Designer.cs
src/Chorus/UI/Misc/ServerSettingsControl.cs
src/LibChorus/Model/ServerSettingsModel.cs

1. Change the ‘Log in’ button to “Log in to continue’.
2. Disable the ‘Log in to continue’ button when logged in and no
edits have been made to either the username or password fields.
3. Changed the Bandwidth and Project Id combo boxes so they are not
clipped.
4. Change the Download button so it remains in the same relative
position when the dialog is resized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/281)

LT-20867: Cleanup Flexbridge login dialog

---

CHANGELOG.md
Directory.Build.props
README.md

This change updates `CHANGELOG.md` - we never released a v5.0.0 despite the entry in the changelog, and adjust the wording to
reality since the non-existing release.
Also up-ing the minor version number because the previous commit added support for netstandard 2.0/.net 6.
+semver:minor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/290)

Update changelog and readme

---

.github/workflows/dotnet.yml
src/LibChorusTests/notes/AnnotationRepositoryTests.cs

This is necessary to trigger a build when pushing a git tag which then will create non-prerelease packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/295)

Run GHA on tag push

---

.github/workflows/dotnet.yml
lgtm.yml
src/Chorus.Tests/Chorus.Tests.csproj
src/Chorus.Tests/ChorusApplicationTests.cs
src/Chorus.Tests/ChorusSystemTests.cs
src/Chorus.Tests/ChorusSystemUsage.cs
src/Chorus.Tests/UI/Clone/TargetFolderControlTests.cs
src/Chorus.Tests/UI/Review/HistoryPanelModelTests.cs
src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
src/ChorusHubTests/ChorusHubTests.csproj
src/ChorusMerge.Tests/ChorusMerge.Tests.csproj
src/LibChorus.TestUtilities/RepositorySetup.cs
src/LibChorusTests/LibChorus.Tests.csproj
src/LibChorusTests/notes/AnnotationRepositoryTests.cs
src/Tests-ChorusPlugin/Tests-ChorusPlugin.csproj

According to the docs[^1] it is recommended to add Microsoft.NET.Test.Sdk to all projects so that the tests can be discovered in VS.
Also add NUnit3TestAdapter to all test projects which is now required[^2] and remove NUnit from Tests-ChorusPlugin where it's not used.
[^1]: https://docs.nunit.org/articles/vs-test-adapter/Adapter-Installation.html
[^2]: https://www.nuget.org/packages/NUnit3TestAdapter/4.2.1#readme-body-tab
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/296)

Add Microsoft.NET.Test.Sdk to test projects

---

src/LibChorus/FileTypeHandlers/audio/AudioFileTypeHandler.cs
src/LibChorus/FileTypeHandlers/image/ImageFileTypeHandler.cs

Fixes #277 
This is in response to users who report a need to add audio and pictures to their project over 1MB in FLEx and Language Forge.  The 1MB is reported to be too small.
Because we don't know practically how this will impact the majority of users, I am happy to introduce this change and evaluate the impact (pluses and minuses) on Language Forge and FLEx users who use Language Depot to collaborate, as well as the increased server storage needed to accommodate the higher limits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/301)

increase audio and picture file size limit to 10MB

---

src/ChorusMerge.Tests/ChorusMerge.Tests.csproj
src/LibChorusTests/LibChorus.Tests.csproj

Bumps [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json) to 13.0.2. <details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/JamesNK/Newtonsoft.Json/releases">Newtonsoft.Json's releases</a>.</em></p> <blockquote>
<h2>13.0.2</h2>
<ul>
<li>New feature - Add support for DateOnly and TimeOnly</li> <li>New feature - Add UnixDateTimeConverter.AllowPreEpoch property</li> <li>New feature - Add copy constructor to JsonSerializerSettings</li> <li>New feature - Add JsonCloneSettings with property to disable copying annotations</li> <li>Change - Add nullable annotation to JToken.ToObject(Type, JsonSerializer)</li> <li>Change - Reduced allocations by reusing boxed values</li> <li>Fix - Fixed MaxDepth when used with ToObject inside of a JsonConverter</li> …

Update to Newtonsoft.JSON to 13.0.2

---

src/Chorus/UI/Clone/GetSharedProjectDlg.Designer.cs

When it is opened from the FieldWorks Welcome dialog (and perhaps other times), it is the only dialog,
so the application disappears from the taskbar entirely.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/315)

Show the Receive Project dialog in the taskbar

---

src/LibChorus/FileTypeHandlers/audio/AudioFileTypeHandler.cs
src/LibChorusTests/FileHandlers/audio/AudioFileTypeHandlerTests.cs

We [recently increased](https://github.com/sillsdev/chorus/pull/301) the max file size for audio and images to 10MB.
But webm is a significant file format in the browser (i.e. Language Forge) and it's not included in the list of known audio file types, so recording audio in LF never actually benefited from this previous change 😲😢,
Webm is a file-type that FLEx supports, so there's no obvious reason to me why we shouldn't include it here, it was simply forgotten.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/319)

Add webm as audio-file-type so it gets 10MB limit

---

src/LibChorus/FileTypeHandlers/ConflictPresenter.cs
src/LibChorus/FileTypeHandlers/lift/LiftChangePresenter.cs
src/LibChorus/merge/xml/generic/Conflict.cs

* While our meta tags are the recommended format for html we sometimes parse the content as xml, so they must be closed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/321)

Generate html header with self closing <meta/>

---

CHANGELOG.md
src/Chorus.Tests/UI/Clone/GetSharedProjectModelTests.cs
src/Chorus/UI/Clone/GetCloneFromInternetDialog.cs
src/Chorus/UI/Clone/GetSharedProjectModel.cs
src/LibChorus/CloneResult.cs

This is necessary so that flexbridge can supply required cloning information and start a repo download without direct/manual user input. This order will come from Fieldworks when launched from CMD or protocol handler with the proper arguments.
Original issue [here](https://github.com/sillsdev/languageforge-lexbox/issues/242).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/325)

Add public StartClone() method

---

CHANGELOG.md
src/LibChorus.TestUtilities/RepositorySetup.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs
src/LibChorus/VcsDrivers/Mercurial/Revision.cs
src/LibChorus/retrieval/RevisionInspector.cs
src/LibChorus/sync/Synchronizer.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgResumeTransportTests.cs

closes #327
transition to json serialization. Refactor Revision.cs to support serialization, Revision has a public surface area so it may effect other applications using Chorus.
Previously Revision had a private field storing an HgRepository class, it's not clear to me if that was just left null when it was read back out but I've resolved that by removing it completely, now anyone calling a method that used to depend on that field will have to provide the repository itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/328)

remove usage of BinaryFormatter

---

CHANGELOG.md
src/ChorusHub/ChorusHub.csproj
src/ChorusMerge.Tests/ChorusMergeTests.cs
src/ChorusMerge/Program.cs
src/Installer/GeneratedMercurial.wxs
src/Installer/GeneratedMercurialExtensions.wxs
src/LibChorus/LibChorus.csproj
src/LibChorus/Utilities/HgProcessOutputReader.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgWrappingTests.cs

https://github.com/sillsdev/Mercurial4Chorus/pull/11 will need to be merged first, then this PR will be able to build.
This updates the included version of Mercurial to 6.5.1, using Python 3 instead of Python 2 (which hasn't received any security fixes in nearly four years, since it went end-of-life on January 1st, 2020).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/329)

Update Chorus to use Mercurial 6.5.1 and Python 3

---

src/LibChorusTests/notes/AnnotationRepositoryTests.cs

The ExternalFileModification_NotifiesIndices_ButSaveDoesNot test [has failed repeatedly](https://github.com/sillsdev/chorus/actions/runs/7211719967/job/19662567825#step:7:2142) on the GHA runner. I suspect the test, that waits 10 seconds to get notified of a filesystem change, may need more time to run. If that isn't enough to fix it, we should remove the test entirely: there's already a comment about how flaky it is, but now it's becoming "reliably flaky", so to speak.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/330)

Try to fix flaky test

---

.github/workflows/ci+cd.yml
Directory.Build.props
src/ChorusMerge/ChorusMerge.csproj
src/Installer/ChorusMergeModule.wixproj
src/LibChorusTests/LibChorus.Tests.csproj
src/LibChorusTests/notes/AnnotationRepositoryTests.cs

LfMerge wants to move to run on net8.0 rather than net6.0; [this will require a chorusmerge build that can run on net8.0](https://github.com/sillsdev/LfMerge/actions/runs/8284368432/job/22670066938).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/332)

Also build for net8.0

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Fixes #337.
Most code paths use ServerSettingsModel.RemovePasswordForLog to replace the user's Send/Receive password with a string of asterisks, but there was one code path where this was missed. This PR fixes that omission. It is also extra-cautious trying to make sure that the debug logging doesn't throw exceptions: if simply calling RemovePasswordForLog ends up throwing an exception somehow, instead of returning the unmodified URI (which might still have a password in it), we simply do not log the URI. This might be over-cautious, but it's probably better to be safe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/339)

Do not log Send/Receive passwords

---

.github/workflows/ci+cd.yml
src/LibChorus/VcsDrivers/Mercurial/HgResumeRestApiServer.cs
src/LibChorus/VcsDrivers/Mercurial/IApiServer.cs
src/LibChorusTests/VcsDrivers/Mercurial/HgResumeRestApiServerTests.cs

previously the port number would be lost when using resumable. Meaning if the url was typed in as localhost:5158 requests would be made to localhost port 80.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/343)

fix case where port number is lost using resumable

---

src/LibChorus/Utilities/HgProcessOutputReader.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Fixes #344.
In rare cases, a thread-scheduling race condition can cause a thread's state to be ThreadState.Stopped even though it hasn't yet executed its `finally` block, which can result in result.StandardOutput or Error not being assigned a string, leaving them null. Furthermore, [the C# docs say not to depend on ThreadState](https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadstate?view=net-8.0#remarks) for synchronizing thread activity. So instead we check for the thread having ended by seeing whether the `finally` block has assigned a value to its Results property; until then, Results is null.
This should guarantee the safety of the existing GetTextFromQuery code, but to be safe we also make sure it can turn null into an empty string.
- - -
This change is [<img …

Avoid NullReferenceExeption in GetTextFromQuery

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Fixes #345.
GetTextFromQuery calls ExecuteErrorsOk, which already logs the value of stdout and stderr to the progress dialog. So there's no point in logging the same value a second time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/347)

Don't duplicate hg process output in GetTextFromQuery

---

src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs

Many times stderr's contents are just a single newline; there's no need to write that to the progress log. We also don't need to write double newlines to the log, so trim the final trailing newline before writing.
Fixes #348.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/349)

No more unnecessary empty "stderr:" lines in log

---

.github/workflows/ci+cd.yml

Fixes #338.
v3 of the upload- and download-artifact actions is deprecated and will stop working about a month from now. Time to switch to v4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/351)

Use upload- and download-artifact v4

---

src/Chorus/UI/Sync/SyncStartModel.cs
src/LibChorus/FileTypeHandlers/text/TextFileTypeHandler.cs
src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs
src/LibChorus/merge/text/PartialTextMerger.cs
src/LibChorusTests/VcsDrivers/Mercurial/MercurialTestUtilities.cs

Fix #355.
Some cases of Platform.IsMono are workarounds for bugs in older versions of mono. Those can probably be removed, but for safety's sake, we'll leave them alone for now.
Other cases are clearly trying to check the platform, to run Linux-only or Windows-only code. Those cases should be replaced by Platform.IsUnix or Platform.IsWindows as appropriate, because nearly everywhere that Chorus is being run on Linux these days, it's running under dotnet rather than mono, and the Platform.IsMono check returns false.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/356)

Replace Platform.IsMono with actual OS checks

---

src/LibChorus/MercurialLocation.cs

Fix #352.
Three env vars are defined, one that sets the path to the Mercurial executable directly (overriding both folder and exe name), one that just overrides the folder and lets Chorus pick the exe name, and one that just overrides the exe name and lets Chorus pick the folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/353)

Allow overriding hg.exe location with env vars

---

.github/workflows/ci+cd.yml
src/Chorus.Tests/Chorus.Tests.csproj
src/ChorusHubTests/ChorusHubTests.csproj
src/ChorusMerge.Tests/ChorusMerge.Tests.csproj
src/ChorusMerge/ChorusMerge.csproj
src/LibChorusTests/LibChorus.Tests.csproj

Now that tests run on three frameworks (net461, net6.0, net8.0), we can save a lot of build time by running each framework's tests in parallel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/354)

Run tests in parallel, one per framework

---

.github/workflows/ci+cd.yml
.github/workflows/test-results.yml
CHANGELOG.md
src/LibChorus/Model/ServerSettingsModel.cs

The x-www-form-urlencoded MIME type says that we're URL-encoding the password, so we need to actually URL-encode the password if we want it to be handled correctly at the other end.
Fixes #324.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/chorus/359)

Correctly encode password in ServerSettingsModel
